/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  navigation?: Array<{
    label: string;
    href: string;
    _type: "navItem";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type JobCategory = {
  _id: string;
  _type: "jobCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type CompanyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "company";
};

export type JobCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "jobCategory";
};

export type Job = {
  _id: string;
  _type: "job";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  company: CompanyReference;
  publishedAt: string;
  available?: boolean;
  categories?: Array<
    {
      _key: string;
    } & JobCategoryReference
  >;
  description?: BlockContent;
  province:
    | "CABA"
    | "Buenos Aires"
    | "Catamarca"
    | "Chaco"
    | "Chubut"
    | "C\xF3rdoba"
    | "Corrientes"
    | "Entre R\xEDos"
    | "Formosa"
    | "Jujuy"
    | "La Pampa"
    | "La Rioja"
    | "Mendoza"
    | "Misiones"
    | "Neuqu\xE9n"
    | "R\xEDo Negro"
    | "Salta"
    | "San Juan"
    | "San Luis"
    | "Santa Cruz"
    | "Santa Fe"
    | "Santiago del Estero"
    | "Tierra del Fuego"
    | "Tucum\xE1n";
  city?: string;
  modality: "presencial" | "remoto" | "hibrido";
  workingDay: "full-time" | "part-time" | "shifts" | "weekends" | "temporary";
  salary?: string;
  tasks?: Array<string>;
  mandatoryRequirements?: Array<string>;
  optionalRequirements?: Array<string>;
  benefits?: Array<string>;
  contactEmail?: string;
  seo?: Seo;
};

export type Company = {
  _id: string;
  _type: "company";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  contactEmail: string;
  website?: string;
  description?: BlockContent;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | BlockContent
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | JobCategory
  | Slug
  | CompanyReference
  | JobCategoryReference
  | Job
  | Company
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../packages/cms-sanity/src/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    title,    description,    logo,    navigation[]{ _key, label, href }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string;
  description: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  navigation: Array<{
    _key: string;
    label: string;
    href: string;
  }> | null;
} | null;

// Source: ../packages/cms-sanity/src/queries.ts
// Variable: JOBS_PAGE_QUERY
// Query: *[_type == "job" && defined(slug.current) && ($province == null || province == $province)]    | order(publishedAt desc) [$start...$end]{   _id,  title,  "slug": slug.current,  publishedAt,  available,  province,  city,  modality,  workingDay,  salary,  "categories": categories[]->{ _id, name },  "company": company->{ name, "slug": slug.current, logo } }
export type JOBS_PAGE_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  publishedAt: string;
  available: boolean | null;
  province:
    | "Buenos Aires"
    | "CABA"
    | "Catamarca"
    | "Chaco"
    | "Chubut"
    | "C\xF3rdoba"
    | "Corrientes"
    | "Entre R\xEDos"
    | "Formosa"
    | "Jujuy"
    | "La Pampa"
    | "La Rioja"
    | "Mendoza"
    | "Misiones"
    | "Neuqu\xE9n"
    | "R\xEDo Negro"
    | "Salta"
    | "San Juan"
    | "San Luis"
    | "Santa Cruz"
    | "Santa Fe"
    | "Santiago del Estero"
    | "Tierra del Fuego"
    | "Tucum\xE1n";
  city: string | null;
  modality: "hibrido" | "presencial" | "remoto";
  workingDay: "full-time" | "part-time" | "shifts" | "temporary" | "weekends";
  salary: string | null;
  categories: Array<{
    _id: string;
    name: string;
  }> | null;
  company: {
    name: string;
    slug: string;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
  };
}>;

// Source: ../packages/cms-sanity/src/queries.ts
// Variable: JOBS_COUNT_QUERY
// Query: count(*[_type == "job" && defined(slug.current) && ($province == null || province == $province)])
export type JOBS_COUNT_QUERY_RESULT = number;

// Source: ../packages/cms-sanity/src/queries.ts
// Variable: JOB_PROVINCES_QUERY
// Query: *[_type == "job" && defined(slug.current)].province
export type JOB_PROVINCES_QUERY_RESULT = Array<
  | "Buenos Aires"
  | "CABA"
  | "Catamarca"
  | "Chaco"
  | "Chubut"
  | "C\xF3rdoba"
  | "Corrientes"
  | "Entre R\xEDos"
  | "Formosa"
  | "Jujuy"
  | "La Pampa"
  | "La Rioja"
  | "Mendoza"
  | "Misiones"
  | "Neuqu\xE9n"
  | "R\xEDo Negro"
  | "Salta"
  | "San Juan"
  | "San Luis"
  | "Santa Cruz"
  | "Santa Fe"
  | "Santiago del Estero"
  | "Tierra del Fuego"
  | "Tucum\xE1n"
>;

// Source: ../packages/cms-sanity/src/queries.ts
// Variable: JOB_QUERY
// Query: *[_type == "job" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  publishedAt,  available,  province,  city,  modality,  workingDay,  salary,  "categories": categories[]->{ _id, name },  "company": company->{ name, "slug": slug.current, logo },    _updatedAt,    description,    tasks,    mandatoryRequirements,    optionalRequirements,    benefits,    "contactEmail": coalesce(contactEmail, company->contactEmail),    seo  }
export type JOB_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  publishedAt: string;
  available: boolean | null;
  province:
    | "Buenos Aires"
    | "CABA"
    | "Catamarca"
    | "Chaco"
    | "Chubut"
    | "C\xF3rdoba"
    | "Corrientes"
    | "Entre R\xEDos"
    | "Formosa"
    | "Jujuy"
    | "La Pampa"
    | "La Rioja"
    | "Mendoza"
    | "Misiones"
    | "Neuqu\xE9n"
    | "R\xEDo Negro"
    | "Salta"
    | "San Juan"
    | "San Luis"
    | "Santa Cruz"
    | "Santa Fe"
    | "Santiago del Estero"
    | "Tierra del Fuego"
    | "Tucum\xE1n";
  city: string | null;
  modality: "hibrido" | "presencial" | "remoto";
  workingDay: "full-time" | "part-time" | "shifts" | "temporary" | "weekends";
  salary: string | null;
  categories: Array<{
    _id: string;
    name: string;
  }> | null;
  company: {
    name: string;
    slug: string;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
  };
  _updatedAt: string;
  description: BlockContent | null;
  tasks: Array<string> | null;
  mandatoryRequirements: Array<string> | null;
  optionalRequirements: Array<string> | null;
  benefits: Array<string> | null;
  contactEmail: string;
  seo: Seo | null;
} | null;

// Source: ../packages/cms-sanity/src/queries.ts
// Variable: JOB_SLUGS_QUERY
// Query: *[_type == "job" && defined(slug.current)]{ "slug": slug.current, _updatedAt }
export type JOB_SLUGS_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: ../packages/cms-sanity/src/queries.ts
// Variable: COMPANIES_QUERY
// Query: *[_type == "company" && defined(slug.current)] | order(name asc){    _id,    name,    "slug": slug.current,    logo  }
export type COMPANIES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
}>;

// Source: ../packages/cms-sanity/src/queries.ts
// Variable: COMPANY_QUERY
// Query: *[_type == "company" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    logo,    website,    contactEmail,    description,    seo,    "jobs": *[_type == "job" && references(^._id) && defined(slug.current)]      | order(publishedAt desc){   _id,  title,  "slug": slug.current,  publishedAt,  available,  province,  city,  modality,  workingDay,  salary,  "categories": categories[]->{ _id, name },  "company": company->{ name, "slug": slug.current, logo } }  }
export type COMPANY_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  website: string | null;
  contactEmail: string;
  description: BlockContent | null;
  seo: Seo | null;
  jobs: Array<{
    _id: string;
    title: string;
    slug: string;
    publishedAt: string;
    available: boolean | null;
    province:
      | "Buenos Aires"
      | "CABA"
      | "Catamarca"
      | "Chaco"
      | "Chubut"
      | "C\xF3rdoba"
      | "Corrientes"
      | "Entre R\xEDos"
      | "Formosa"
      | "Jujuy"
      | "La Pampa"
      | "La Rioja"
      | "Mendoza"
      | "Misiones"
      | "Neuqu\xE9n"
      | "R\xEDo Negro"
      | "Salta"
      | "San Juan"
      | "San Luis"
      | "Santa Cruz"
      | "Santa Fe"
      | "Santiago del Estero"
      | "Tierra del Fuego"
      | "Tucum\xE1n";
    city: string | null;
    modality: "hibrido" | "presencial" | "remoto";
    workingDay: "full-time" | "part-time" | "shifts" | "temporary" | "weekends";
    salary: string | null;
    categories: Array<{
      _id: string;
      name: string;
    }> | null;
    company: {
      name: string;
      slug: string;
      logo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
      } | null;
    };
  }>;
} | null;

// Source: ../packages/cms-sanity/src/queries.ts
// Variable: COMPANY_SLUGS_QUERY
// Query: *[_type == "company" && defined(slug.current)]{ "slug": slug.current, _updatedAt }
export type COMPANY_SLUGS_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    title,\n    description,\n    logo,\n    navigation[]{ _key, label, href }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "job" && defined(slug.current) && ($province == null || province == $province)]\n    | order(publishedAt desc) [$start...$end]{ \n  _id,\n  title,\n  "slug": slug.current,\n  publishedAt,\n  available,\n  province,\n  city,\n  modality,\n  workingDay,\n  salary,\n  "categories": categories[]->{ _id, name },\n  "company": company->{ name, "slug": slug.current, logo }\n }\n': JOBS_PAGE_QUERY_RESULT;
    '\n  count(*[_type == "job" && defined(slug.current) && ($province == null || province == $province)])\n': JOBS_COUNT_QUERY_RESULT;
    '\n  *[_type == "job" && defined(slug.current)].province\n': JOB_PROVINCES_QUERY_RESULT;
    '\n  *[_type == "job" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  publishedAt,\n  available,\n  province,\n  city,\n  modality,\n  workingDay,\n  salary,\n  "categories": categories[]->{ _id, name },\n  "company": company->{ name, "slug": slug.current, logo }\n,\n    _updatedAt,\n    description,\n    tasks,\n    mandatoryRequirements,\n    optionalRequirements,\n    benefits,\n    "contactEmail": coalesce(contactEmail, company->contactEmail),\n    seo\n  }\n': JOB_QUERY_RESULT;
    '\n  *[_type == "job" && defined(slug.current)]{ "slug": slug.current, _updatedAt }\n': JOB_SLUGS_QUERY_RESULT;
    '\n  *[_type == "company" && defined(slug.current)] | order(name asc){\n    _id,\n    name,\n    "slug": slug.current,\n    logo\n  }\n': COMPANIES_QUERY_RESULT;
    '\n  *[_type == "company" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    logo,\n    website,\n    contactEmail,\n    description,\n    seo,\n    "jobs": *[_type == "job" && references(^._id) && defined(slug.current)]\n      | order(publishedAt desc){ \n  _id,\n  title,\n  "slug": slug.current,\n  publishedAt,\n  available,\n  province,\n  city,\n  modality,\n  workingDay,\n  salary,\n  "categories": categories[]->{ _id, name },\n  "company": company->{ name, "slug": slug.current, logo }\n }\n  }\n': COMPANY_QUERY_RESULT;
    '\n  *[_type == "company" && defined(slug.current)]{ "slug": slug.current, _updatedAt }\n': COMPANY_SLUGS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
