packages:
  - web
  - studio
  - packages/*

overrides:
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  react: 19.3.0
  react-dom: 19.3.0

allowBuilds:
  esbuild: true
  sharp: true
  msw: false
  unrs-resolver: false
