// Mock content for local development and demos. Companies are fictional and
// emails use the reserved `.example` TLD so nobody gets real CVs by mistake.
// Images are free Unsplash photos, used as temporary logos.

export type SeedCategory = {key: string; name: string}

export type SeedCompany = {
  key: string
  name: string
  contactEmail: string
  website?: string
  unsplashId: string
  logoAlt: string
  description: string[]
}

export type SeedJob = {
  title: string
  company: string
  categories: string[]
  province: string
  city: string
  modality: 'presencial' | 'remoto' | 'hibrido'
  workingDay: 'full-time' | 'part-time' | 'shifts' | 'weekends' | 'temporary'
  salary: string
  available: boolean
  daysAgo: number
  description: string[]
  tasks: string[]
  mandatoryRequirements: string[]
  optionalRequirements: string[]
  benefits: string[]
}

export const categories: SeedCategory[] = [
  {key: 'atencion', name: 'Atención al cliente'},
  {key: 'ventas', name: 'Ventas y comercio'},
  {key: 'logistica', name: 'Logística y depósito'},
  {key: 'gastronomia', name: 'Gastronomía'},
  {key: 'administracion', name: 'Administración'},
  {key: 'limpieza', name: 'Limpieza y mantenimiento'},
  {key: 'transporte', name: 'Transporte'},
  {key: 'call-center', name: 'Call center'},
  {key: 'primer-empleo', name: 'Primer empleo'},
]

export const companies: SeedCompany[] = [
  {
    key: 'don-ramiro',
    name: 'Supermercados Don Ramiro',
    contactEmail: 'rrhh@donramiro.example',
    unsplashId: '1542838132-92c53300491e',
    logoAlt: 'Góndola de frutas y verduras',
    description: [
      'Cadena de supermercados de barrio con 14 sucursales en el conurbano bonaerense.',
      'Buscamos personas con ganas de aprender: la mayoría de nuestros encargados empezaron como repositores.',
    ],
  },
  {
    key: 'pampa-cargas',
    name: 'Pampa Cargas Logística',
    contactEmail: 'seleccion@pampacargas.example',
    unsplashId: '1586528116311-ad8dd3c8310d',
    logoAlt: 'Depósito con cajas en estanterías',
    description: [
      'Operador logístico con centros de distribución en Buenos Aires, Córdoba y Rosario.',
      'Capacitamos en manejo de stock, picking y uso de autoelevadores.',
    ],
  },
  {
    key: 'molinos-del-sur',
    name: 'Café Molinos del Sur',
    contactEmail: 'trabaja@molinosdelsur.example',
    unsplashId: '1509042239860-f550ce710b93',
    logoAlt: 'Tazas de café con arte latte',
    description: [
      'Cafetería de especialidad con locales en Córdoba y Mendoza.',
      'Te enseñamos desde cero el oficio de barista.',
    ],
  },
  {
    key: 'la-tranquera',
    name: 'Parrilla La Tranquera',
    contactEmail: 'personal@latranquera.example',
    unsplashId: '1517248135467-4c7edcad34c4',
    logoAlt: 'Salón de restaurante con mesas de madera',
    description: [
      'Restaurante familiar de cocina argentina en San Telmo y Palermo.',
      'Equipo joven, buen ambiente y posibilidades reales de crecimiento.',
    ],
  },
  {
    key: 'conecta',
    name: 'Conecta Contact Center',
    contactEmail: 'busquedas@conectacc.example',
    unsplashId: '1522071820081-009f0129c71c',
    logoAlt: 'Personas trabajando con notebooks',
    description: [
      'Centro de atención al cliente para empresas de servicios, telecomunicaciones y bancos.',
      'Capacitación paga de dos semanas antes de empezar a atender.',
    ],
  },
  {
    key: 'andina',
    name: 'Limpiezas Integrales Andina',
    contactEmail: 'rrhh@limpiezasandina.example',
    unsplashId: '1581578731548-c64695cc6952',
    logoAlt: 'Persona limpiando una ventana',
    description: [
      'Servicios de limpieza y mantenimiento para oficinas, hospitales y edificios en Salta y Tucumán.',
    ],
  },
  {
    key: 'ruta-40',
    name: 'Transportes Ruta Cuarenta',
    contactEmail: 'choferes@rutacuarenta.example',
    unsplashId: '1519003722824-194d4455a60c',
    logoAlt: 'Camión en una ruta de montaña',
    description: [
      'Empresa de transporte de cargas generales con base en Neuquén.',
      'Acompañamos a quienes recién obtienen su licencia profesional.',
    ],
  },
  {
    key: 'tienda-urbana',
    name: 'Tienda Urbana Indumentaria',
    contactEmail: 'empleo@tiendaurbana.example',
    unsplashId: '1441986300917-64674bd600d8',
    logoAlt: 'Local de ropa con estanterías',
    description: ['Marca de ropa urbana con locales en shoppings de CABA, La Plata y Rosario.'],
  },
  {
    key: 'ferreyra',
    name: 'Estudio Contable Ferreyra y Asociados',
    contactEmail: 'pasantias@estudioferreyra.example',
    unsplashId: '1454165804606-c3d57bc86b40',
    logoAlt: 'Escritorio con notebook y anotaciones',
    description: [
      'Estudio contable que asesora a pymes y monotributistas.',
      'Tomamos estudiantes de los primeros años de Ciencias Económicas.',
    ],
  },
]

export const jobs: SeedJob[] = [
  {
    title: 'Repositor/a de góndola',
    company: 'don-ramiro',
    categories: ['ventas', 'primer-empleo'],
    province: 'Buenos Aires',
    city: 'Lomas de Zamora',
    modality: 'presencial',
    workingDay: 'full-time',
    salary: '$980.000 brutos mensuales',
    available: true,
    daysAgo: 1,
    description: [
      'Sumamos repositores para nuestra sucursal de Lomas de Zamora. No hace falta experiencia: la capacitación es en el local, junto a un compañero con experiencia.',
    ],
    tasks: [
      'Reponer mercadería en góndolas y heladeras',
      'Controlar fechas de vencimiento',
      'Mantener el orden y la limpieza del sector',
      'Ayudar a los clientes a encontrar productos',
    ],
    mandatoryRequirements: ['Secundario completo o en curso', 'Mayor de 18 años', 'Vivir en zona sur'],
    optionalRequirements: ['Experiencia en comercios'],
    benefits: ['Descuento del 15% en compras', 'Obra social', 'Plan de carrera a encargado de sector'],
  },
  {
    title: 'Cajero/a para sucursal',
    company: 'don-ramiro',
    categories: ['atencion', 'ventas', 'primer-empleo'],
    province: 'Buenos Aires',
    city: 'Quilmes',
    modality: 'presencial',
    workingDay: 'shifts',
    salary: '$1.020.000 brutos mensuales',
    available: true,
    daysAgo: 3,
    description: [
      'Buscamos cajeros para turnos rotativos de mañana y tarde. Si te gusta el trato con la gente, este puesto es para vos.',
    ],
    tasks: ['Cobrar en efectivo y con medios electrónicos', 'Hacer el arqueo de caja al cierre del turno', 'Atender consultas de clientes'],
    mandatoryRequirements: ['Secundario completo', 'Disponibilidad para turnos rotativos'],
    optionalRequirements: ['Manejo básico de PC'],
    benefits: ['Presentismo', 'Descuento en compras', 'Uniforme provisto por la empresa'],
  },
  {
    title: 'Operario/a de depósito',
    company: 'pampa-cargas',
    categories: ['logistica', 'primer-empleo'],
    province: 'Buenos Aires',
    city: 'Pilar',
    modality: 'presencial',
    workingDay: 'full-time',
    salary: '$1.150.000 brutos mensuales',
    available: true,
    daysAgo: 2,
    description: [
      'Incorporamos operarios para el centro de distribución de Pilar. No se requiere experiencia: te capacitamos en picking, armado de pedidos y seguridad e higiene.',
    ],
    tasks: ['Preparar pedidos (picking)', 'Carga y descarga de camiones', 'Control de mercadería recibida', 'Etiquetado y embalaje'],
    mandatoryRequirements: ['Secundario completo', 'Buena condición física', 'Vivir a menos de 30 km de Pilar'],
    optionalRequirements: ['Carnet de autoelevador'],
    benefits: ['Transporte desde estación Pilar', 'Comedor en planta', 'Obra social'],
  },
  {
    title: 'Auxiliar de logística',
    company: 'pampa-cargas',
    categories: ['logistica', 'administracion'],
    province: 'Córdoba',
    city: 'Córdoba Capital',
    modality: 'presencial',
    workingDay: 'full-time',
    salary: '$1.100.000 brutos mensuales',
    available: true,
    daysAgo: 6,
    description: [
      'Buscamos un auxiliar para acompañar al equipo de tráfico en la planificación de entregas y el seguimiento de pedidos.',
    ],
    tasks: ['Cargar remitos en el sistema', 'Coordinar horarios de entrega con clientes', 'Hacer seguimiento de envíos'],
    mandatoryRequirements: ['Secundario completo', 'Manejo de Excel básico'],
    optionalRequirements: ['Estudiante de carreras de logística o administración'],
    benefits: ['Horario fijo de lunes a viernes', 'Capacitación en sistemas de gestión'],
  },
  {
    title: 'Ayudante de barista',
    company: 'molinos-del-sur',
    categories: ['gastronomia', 'atencion', 'primer-empleo'],
    province: 'Córdoba',
    city: 'Nueva Córdoba',
    modality: 'presencial',
    workingDay: 'part-time',
    salary: '$620.000 mensuales + propinas',
    available: true,
    daysAgo: 4,
    description: [
      'Media jornada ideal para estudiantes. Te enseñamos a preparar café de especialidad y a atender la barra.',
    ],
    tasks: ['Preparar bebidas a base de café', 'Atender la barra y tomar pedidos', 'Mantener limpia la máquina y el sector'],
    mandatoryRequirements: ['Disponibilidad de 6 horas por la tarde', 'Buena predisposición para atender al público'],
    optionalRequirements: ['Curso de manipulación de alimentos'],
    benefits: ['Propinas', 'Curso de barista pago por la empresa', 'Comida en el turno'],
  },
  {
    title: 'Mozo/a para turno noche',
    company: 'la-tranquera',
    categories: ['gastronomia', 'atencion'],
    province: 'CABA',
    city: 'San Telmo',
    modality: 'presencial',
    workingDay: 'shifts',
    salary: '$850.000 mensuales + propinas',
    available: true,
    daysAgo: 2,
    description: ['Buscamos mozos para el turno noche de miércoles a domingo. No pedimos experiencia, sí ganas y buena actitud.'],
    tasks: ['Recibir a los clientes y tomar pedidos', 'Servir mesas', 'Armar y desarmar el salón'],
    mandatoryRequirements: ['Disponibilidad nocturna y fines de semana', 'Mayor de 18 años'],
    optionalRequirements: ['Inglés básico para atender turistas'],
    benefits: ['Propinas repartidas', 'Cena en el turno', 'Viáticos'],
  },
  {
    title: 'Ayudante de cocina',
    company: 'la-tranquera',
    categories: ['gastronomia', 'primer-empleo'],
    province: 'CABA',
    city: 'Palermo',
    modality: 'presencial',
    workingDay: 'full-time',
    salary: '$900.000 brutos mensuales',
    available: false,
    daysAgo: 20,
    description: ['Búsqueda finalizada. Gracias a todas las personas que se postularon.'],
    tasks: ['Preparación de ensaladas y guarniciones', 'Lavado de vajilla', 'Orden de la cámara de frío'],
    mandatoryRequirements: ['Libreta sanitaria vigente'],
    optionalRequirements: [],
    benefits: ['Comida en el turno'],
  },
  {
    title: 'Operador/a de atención telefónica',
    company: 'conecta',
    categories: ['call-center', 'atencion', 'primer-empleo'],
    province: 'CABA',
    city: 'Microcentro',
    modality: 'hibrido',
    workingDay: 'part-time',
    salary: '$780.000 brutos por 6 horas',
    available: true,
    daysAgo: 1,
    description: [
      'Atención de clientes de una empresa de internet. Las dos primeras semanas de capacitación son pagas y presenciales; después podés trabajar dos días desde tu casa.',
    ],
    tasks: ['Atender llamadas entrantes', 'Registrar reclamos en el sistema', 'Derivar casos técnicos al área correspondiente'],
    mandatoryRequirements: ['Secundario completo', 'Buena dicción', 'Conexión a internet estable para los días remotos'],
    optionalRequirements: ['Experiencia en atención al cliente'],
    benefits: ['Capacitación paga', 'Bono por objetivos', 'Horario fijo'],
  },
  {
    title: 'Asesor/a comercial por chat',
    company: 'conecta',
    categories: ['call-center', 'ventas'],
    province: 'Santa Fe',
    city: 'Rosario',
    modality: 'remoto',
    workingDay: 'part-time',
    salary: '$700.000 + comisiones',
    available: true,
    daysAgo: 5,
    description: ['Trabajo 100% remoto respondiendo consultas de venta por WhatsApp y chat web.'],
    tasks: ['Responder consultas de potenciales clientes', 'Cargar ventas en el CRM', 'Hacer seguimiento de presupuestos'],
    mandatoryRequirements: ['Buena ortografía', 'Computadora propia'],
    optionalRequirements: ['Experiencia en ventas'],
    benefits: ['Trabajo desde casa', 'Comisiones sin techo'],
  },
  {
    title: 'Personal de limpieza para oficinas',
    company: 'andina',
    categories: ['limpieza', 'primer-empleo'],
    province: 'Salta',
    city: 'Salta Capital',
    modality: 'presencial',
    workingDay: 'part-time',
    salary: '$560.000 mensuales',
    available: true,
    daysAgo: 7,
    description: ['Turno de 18 a 22 h en edificios de oficinas del centro de Salta.'],
    tasks: ['Limpieza de oficinas, baños y espacios comunes', 'Reposición de insumos'],
    mandatoryRequirements: ['Disponibilidad horaria de lunes a viernes por la tarde'],
    optionalRequirements: [],
    benefits: ['Ropa de trabajo', 'ART y obra social'],
  },
  {
    title: 'Auxiliar de mantenimiento',
    company: 'andina',
    categories: ['limpieza'],
    province: 'Tucumán',
    city: 'San Miguel de Tucumán',
    modality: 'presencial',
    workingDay: 'full-time',
    salary: '$950.000 brutos mensuales',
    available: true,
    daysAgo: 10,
    description: ['Tareas de mantenimiento general en un complejo de oficinas. Te acompaña un técnico con experiencia.'],
    tasks: ['Cambio de luminarias', 'Pintura y reparaciones menores', 'Control de equipos de aire acondicionado'],
    mandatoryRequirements: ['Secundario completo'],
    optionalRequirements: ['Conocimientos básicos de electricidad'],
    benefits: ['Capacitación en oficios', 'Obra social'],
  },
  {
    title: 'Chofer de reparto con licencia profesional',
    company: 'ruta-40',
    categories: ['transporte'],
    province: 'Neuquén',
    city: 'Neuquén Capital',
    modality: 'presencial',
    workingDay: 'full-time',
    salary: '$1.400.000 brutos mensuales',
    available: true,
    daysAgo: 3,
    description: [
      'Reparto urbano con utilitario. Tomamos choferes que recién sacaron la licencia profesional; los primeros viajes los hacés acompañado.',
    ],
    tasks: ['Entregar mercadería a clientes', 'Controlar la carga', 'Completar la hoja de ruta'],
    mandatoryRequirements: ['Licencia de conducir profesional B2 o superior', 'Mayor de 21 años'],
    optionalRequirements: ['Conocer la ciudad de Neuquén'],
    benefits: ['Viáticos', 'Vehículo de la empresa', 'Obra social'],
  },
  {
    title: 'Peón de carga y descarga',
    company: 'ruta-40',
    categories: ['transporte', 'logistica', 'primer-empleo'],
    province: 'Río Negro',
    city: 'Cipolletti',
    modality: 'presencial',
    workingDay: 'temporary',
    salary: '$45.000 por jornada',
    available: true,
    daysAgo: 8,
    description: ['Trabajo eventual durante la temporada de fruta (diciembre a marzo), con posibilidad de continuidad.'],
    tasks: ['Carga y descarga de camiones', 'Armado de pallets'],
    mandatoryRequirements: ['Buena condición física'],
    optionalRequirements: [],
    benefits: ['Pago semanal', 'Posibilidad de pase a planta'],
  },
  {
    title: 'Vendedor/a de salón',
    company: 'tienda-urbana',
    categories: ['ventas', 'atencion', 'primer-empleo'],
    province: 'CABA',
    city: 'Caballito',
    modality: 'presencial',
    workingDay: 'part-time',
    salary: '$650.000 + comisiones',
    available: true,
    daysAgo: 2,
    description: ['Buscamos vendedores para nuestro local en un shopping de Caballito. Ideal primer trabajo.'],
    tasks: ['Asesorar a clientes', 'Ordenar el local y el depósito', 'Cobrar en caja cuando sea necesario'],
    mandatoryRequirements: ['Disponibilidad para fines de semana', 'Secundario completo o en curso'],
    optionalRequirements: ['Interés por la moda'],
    benefits: ['Descuento en ropa', 'Comisiones por venta'],
  },
  {
    title: 'Promotor/a de fin de semana',
    company: 'tienda-urbana',
    categories: ['ventas'],
    province: 'Buenos Aires',
    city: 'La Plata',
    modality: 'presencial',
    workingDay: 'weekends',
    salary: '$40.000 por jornada',
    available: true,
    daysAgo: 9,
    description: ['Acciones de promoción en shoppings los sábados y domingos.'],
    tasks: ['Invitar a clientes a conocer la nueva colección', 'Entregar folletos y cupones'],
    mandatoryRequirements: ['Disponibilidad sábados y domingos'],
    optionalRequirements: [],
    benefits: ['Pago al finalizar cada acción'],
  },
  {
    title: 'Pasante administrativo/a',
    company: 'ferreyra',
    categories: ['administracion', 'primer-empleo'],
    province: 'Mendoza',
    city: 'Mendoza Capital',
    modality: 'hibrido',
    workingDay: 'part-time',
    salary: '$520.000 (asignación estímulo)',
    available: true,
    daysAgo: 4,
    description: ['Pasantía de 4 horas diarias para estudiantes de Ciencias Económicas, con tutor asignado.'],
    tasks: ['Carga de comprobantes', 'Archivo de documentación', 'Atención de consultas de clientes por mail'],
    mandatoryRequirements: ['Ser estudiante regular de Contador, Administración o afines'],
    optionalRequirements: ['Manejo de Excel intermedio'],
    benefits: ['Horario compatible con la facultad', 'Dos días de trabajo remoto'],
  },
  {
    title: 'Recepcionista',
    company: 'ferreyra',
    categories: ['administracion', 'atencion'],
    province: 'Mendoza',
    city: 'Godoy Cruz',
    modality: 'presencial',
    workingDay: 'full-time',
    salary: '$880.000 brutos mensuales',
    available: false,
    daysAgo: 25,
    description: ['Búsqueda finalizada.'],
    tasks: ['Atender el teléfono', 'Recibir a los clientes', 'Organizar la agenda de reuniones'],
    mandatoryRequirements: ['Secundario completo'],
    optionalRequirements: [],
    benefits: ['Horario de oficina'],
  },
  {
    title: 'Data entry',
    company: 'ferreyra',
    categories: ['administracion', 'primer-empleo'],
    province: 'Buenos Aires',
    city: 'Mar del Plata',
    modality: 'remoto',
    workingDay: 'part-time',
    salary: '$600.000 mensuales',
    available: true,
    daysAgo: 12,
    description: ['Carga de datos contables desde tu casa, con horario flexible.'],
    tasks: ['Cargar facturas en el sistema contable', 'Verificar datos de proveedores'],
    mandatoryRequirements: ['Computadora propia', 'Muy buena atención al detalle'],
    optionalRequirements: ['Conocimientos de facturación'],
    benefits: ['Horario flexible', '100% remoto'],
  },
]

export const siteSettings = {
  title: 'WorkStart',
  description: 'Ofertas de trabajo sin experiencia en Argentina. Contactá directamente con las empresas.',
  navigation: [
    {label: 'Trabajos', href: '/todos-los-trabajos'},
    {label: 'Sobre nosotros', href: '/sobre-nosotros'},
    {label: 'Contacto', href: '/contacto'},
  ],
}
